EREEFSII-1111 Install old versions from github releases, prioritise LODE rendering, fix use of env vars

diff --git a/server/Dockerfile b/server/Dockerfile
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -2,18 +2,21 @@ ARG ONTOLOGY_VERSION="latest"
 
 FROM eclipse-temurin:8 as converter
 
+SHELL ["/bin/bash", "-c"]
+
 WORKDIR /rdf2rdf
 COPY server/*.jar ./
 
 WORKDIR /dpn
 
-# Include the local ontology files in TTL->RDF conversion efforts
+# Install the latest .ttl files
 ARG ONTOLOGY_VERSION
 COPY dpn*.ttl ./${ONTOLOGY_VERSION}/
 
-# Perform TTL -> RDF conversions
-SHELL ["/bin/bash", "-c"]
-RUN for TTL_PATH in $(find ./ -type f -name '*.ttl'); do \
+# Compile the latest .ttl files to .rdf
+# (Will fail the build if there are any syntax errors)
+RUN cd "${ONTOLOGY_VERSION}"; \
+    for TTL_PATH in $(find ./ -type f -name '*.ttl'); do \
         TTL_PATH=$(realpath "${TTL_PATH}"); \
         RDF_PATH="${TTL_PATH%.ttl}.rdf"; \
         RESULT=$(java -jar /rdf2rdf/rdf2rdf-1.0.1-2.3.1.jar "${TTL_PATH}" "${RDF_PATH}" 2>&1);\
@@ -21,13 +24,23 @@ RUN for TTL_PATH in $(find ./ -type f -name '*.ttl'); do \
         echo "${RESULT}"; \
     done
 
+# Produce a tarball of the latest .ttl and .rdf files
+# This is suitable for use as a GitHub release binary
+RUN cd "${ONTOLOGY_VERSION}" \
+    && tar -zcvf "/dpn/dpn_ontology_${ONTOLOGY_VERSION}.tar.gz" .
+
 # Install some historically-significant versions of the precompiled ontology
 # that have been released elsewhere
-ARG CSIRO_COASTS_VERSIONS="v0.7.2.26 v0.7.1.9 v0.6.1.24 v0.4.0.19"
-RUN CCVS="${CSIRO_COASTS_VERSIONS}"; \
-    for CCV in $CCVS; do \
-        mkdir "/dpn/${CCV}" \
-        && curl -s "https://build.csiro-coasts.net/archive/DPN-ontology/dpn_ontology_${CCV}.tar.gz" | tar -zxvf - -C "/dpn/${CCV}"; \
+ARG OLD_VERSIONS="v0.7.2 v0.7.1 v0.6.1.24 v0.4.0.19"
+ENV OLD_VERSIONS="${OLD_VERSIONS}"
+RUN --mount=target=/downloads,type=cache,sharing=locked \
+    cd /downloads && \
+    for VERSION in $OLD_VERSIONS; do \
+        URL="https://github.com/eReefs/dpn-ontology/releases/download/${VERSION}/dpn_ontology_${VERSION}.tar.gz"; \
+        wget --timestamping "${URL}" && \
+        mkdir -p "/dpn/${VERSION}" && \
+        tar -zxvf "dpn_ontology_${VERSION}.tar.gz" -C "/dpn/${VERSION}"; \
+        if [ ! -f "/dpn/${VERSION}/dpn.ttl" ]; then >&2 echo "dpn.ttl missing for ${VERSION}"; exit -1; fi; \
     done
 
 #------------------------------------------------------------------------------
@@ -53,10 +66,13 @@ RUN chmod 0755 ./make_version_symlinks.sh \
     && rm make_version_symlinks.sh
 
 # Set default values for the environment variables used in the .htaccess file
-ENV CONTACT_EMAIL="admin@example.com" \
-    CURRENT_VERSION="latest" \
-    ENABLE_ACCESS_LOGGING="true" \
-    ENDPOINT="" \
+ARG ONTOLOGY_VERSION
+ENV ACCESS_LOG_PATH="/proc/self/fd/1" \
+    ERROR_LOG_LEVEL="warn" \
+    CONTACT_EMAIL="admin@example.com" \
     FAVICON_URL="/favicon.ico" \
+    CURRENT_VERSION="${ONTOLOGY_VERSION}" \
+    LATEST_VERSION="${ONTOLOGY_VERSION}" \
     LODE_BASEURL="" \
-    LOG_LEVEL="warn"
+    LODE_PROXY="true" \
+    PATH_PREFIX=""
